#!/usr/bin/env python3
"""Generate proper vocabulary for grades 2-9."""

import json
import os
import glob

GRADE_1 = [
    {"en": "apple", "phon": "/ˈæp.əl/", "cn": "苹果"},
    {"en": "banana", "phon": "/bəˈnæn.ə/", "cn": "香蕉"},
    {"en": "cat", "phon": "/kæt/", "cn": "猫"},
    {"en": "dog", "phon": "/dɒɡ/", "cn": "狗"},
    {"en": "fish", "phon": "/fɪʃ/", "cn": "鱼"},
    {"en": "bird", "phon": "/bɜːd/", "cn": "鸟"},
    {"en": "one", "phon": "/wʌn/", "cn": "一"},
    {"en": "two", "phon": "/tuː/", "cn": "二"},
    {"en": "three", "phon": "/θriː/", "cn": "三"},
    {"en": "four", "phon": "/fɔːr/", "cn": "四"},
    {"en": "five", "phon": "/faɪv/", "cn": "五"},
    {"en": "six", "phon": "/sɪks/", "cn": "六"},
    {"en": "seven", "phon": "/ˈsev.ən/", "cn": "七"},
    {"en": "eight", "phon": "/eɪt/", "cn": "八"},
    {"en": "nine", "phon": "/naɪn/", "cn": "九"},
    {"en": "ten", "phon": "/ten/", "cn": "十"},
    {"en": "red", "phon": "/red/", "cn": "红色"},
    {"en": "blue", "phon": "/bluː/", "cn": "蓝色"},
    {"en": "green", "phon": "/ɡriːn/", "cn": "绿色"},
    {"en": "yellow", "phon": "/ˈjel.əʊ/", "cn": "黄色"},
    {"en": "black", "phon": "/blæk/", "cn": "黑色"},
    {"en": "white", "phon": "/waɪt/", "cn": "白色"},
    {"en": "mom", "phon": "/mɒm/", "cn": "妈妈"},
    {"en": "dad", "phon": "/dæd/", "cn": "爸爸"},
    {"en": "brother", "phon": "/ˈbrʌð.ər/", "cn": "兄弟"},
    {"en": "sister", "phon": "/ˈsɪs.tər/", "cn": "姐妹"},
    {"en": "sun", "phon": "/sʌn/", "cn": "太阳"},
    {"en": "moon", "phon": "/muːn/", "cn": "月亮"},
    {"en": "star", "phon": "/stɑːr/", "cn": "星星"},
    {"en": "tree", "phon": "/triː/", "cn": "树"},
    {"en": "flower", "phon": "/ˈflaʊ.ər/", "cn": "花"},
    {"en": "water", "phon": "/ˈwɔː.tər/", "cn": "水"},
    {"en": "milk", "phon": "/mɪlk/", "cn": "牛奶"},
    {"en": "bread", "phon": "/bred/", "cn": "面包"},
    {"en": "egg", "phon": "/eɡ/", "cn": "鸡蛋"},
    {"en": "rice", "phon": "/raɪs/", "cn": "米饭"},
    {"en": "hand", "phon": "/hænd/", "cn": "手"},
    {"en": "eye", "phon": "/aɪ/", "cn": "眼睛"},
    {"en": "ear", "phon": "/ɪər/", "cn": "耳朵"},
    {"en": "nose", "phon": "/nəʊz/", "cn": "鼻子"},
    {"en": "mouth", "phon": "/maʊθ/", "cn": "嘴巴"},
    {"en": "foot", "phon": "/fʊt/", "cn": "脚"},
    {"en": "head", "phon": "/hed/", "cn": "头"},
    {"en": "big", "phon": "/bɪɡ/", "cn": "大"},
    {"en": "small", "phon": "/smɔːl/", "cn": "小"},
    {"en": "happy", "phon": "/ˈhæp.i/", "cn": "开心"},
    {"en": "sad", "phon": "/sæd/", "cn": "伤心"},
    {"en": "yes", "phon": "/jes/", "cn": "是"},
    {"en": "no", "phon": "/nəʊ/", "cn": "不是"},
    {"en": "up", "phon": "/ʌp/", "cn": "上"},
    {"en": "school", "phon": "/skuːl/", "cn": "学校"},
    {"en": "teacher", "phon": "/ˈtiː.tʃər/", "cn": "老师"},
    {"en": "book", "phon": "/bʊk/", "cn": "书"},
    {"en": "pen", "phon": "/pen/", "cn": "笔"},
    {"en": "desk", "phon": "/desk/", "cn": "书桌"},
    {"en": "chair", "phon": "/tʃeər/", "cn": "椅子"},
    {"en": "door", "phon": "/dɔːr/", "cn": "门"},
    {"en": "window", "phon": "/ˈwɪn.dəʊ/", "cn": "窗户"},
    {"en": "house", "phon": "/haʊs/", "cn": "房子"},
    {"en": "car", "phon": "/kɑːr/", "cn": "汽车"},
    {"en": "bus", "phon": "/bʌs/", "cn": "公交车"},
    {"en": "bike", "phon": "/baɪk/", "cn": "自行车"},
    {"en": "run", "phon": "/rʌn/", "cn": "跑"},
    {"en": "walk", "phon": "/wɔːk/", "cn": "走"},
    {"en": "jump", "phon": "/dʒʌmp/", "cn": "跳"},
    {"en": "eat", "phon": "/iːt/", "cn": "吃"},
    {"en": "drink", "phon": "/drɪŋk/", "cn": "喝"},
    {"en": "sleep", "phon": "/sliːp/", "cn": "睡觉"},
    {"en": "play", "phon": "/pleɪ/", "cn": "玩"},
    {"en": "read", "phon": "/riːd/", "cn": "读"},
    {"en": "write", "phon": "/raɪt/", "cn": "写"},
    {"en": "sing", "phon": "/sɪŋ/", "cn": "唱歌"},
    {"en": "dance", "phon": "/dæns/", "cn": "跳舞"},
    {"en": "draw", "phon": "/drɔː/", "cn": "画画"},
    {"en": "swim", "phon": "/swɪm/", "cn": "游泳"},
    {"en": "fly", "phon": "/flaɪ/", "cn": "飞"},
    {"en": "open", "phon": "/ˈəʊ.pən/", "cn": "打开"},
    {"en": "close", "phon": "/kləʊz/", "cn": "关闭"},
    {"en": "hot", "phon": "/hɒt/", "cn": "热"},
    {"en": "cold", "phon": "/kəʊld/", "cn": "冷"},
    {"en": "warm", "phon": "/wɔːm/", "cn": "温暖"},
    {"en": "cool", "phon": "/kuːl/", "cn": "凉爽"},
    {"en": "long", "phon": "/lɒŋ/", "cn": "长"},
    {"en": "short", "phon": "/ʃɔːt/", "cn": "短"},
    {"en": "tall", "phon": "/tɔːl/", "cn": "高"},
    {"en": "fat", "phon": "/fæt/", "cn": "胖"},
    {"en": "thin", "phon": "/θɪn/", "cn": "瘦"},
    {"en": "new", "phon": "/njuː/", "cn": "新"},
    {"en": "old", "phon": "/əʊld/", "cn": "旧"},
    {"en": "good", "phon": "/ɡʊd/", "cn": "好"},
    {"en": "bad", "phon": "/bæd/", "cn": "坏"},
    {"en": "fast", "phon": "/fæst/", "cn": "快"},
    {"en": "slow", "phon": "/sləʊ/", "cn": "慢"},
    {"en": "love", "phon": "/lʌv/", "cn": "爱"},
    {"en": "like", "phon": "/laɪk/", "cn": "喜欢"},
    {"en": "want", "phon": "/wɒnt/", "cn": "想要"},
    {"en": "have", "phon": "/hæv/", "cn": "有"},
    {"en": "come", "phon": "/kʌm/", "cn": "来"},
    {"en": "go", "phon": "/ɡəʊ/", "cn": "去"},
    {"en": "see", "phon": "/siː/", "cn": "看"},
    {"en": "morning", "phon": "/ˈmɔːn.ɪŋ/", "cn": "早上"},
    {"en": "afternoon", "phon": "/ˌæf.təˈnuːn/", "cn": "下午"},
    {"en": "evening", "phon": "/ˈiːv.nɪŋ/", "cn": "晚上"},
    {"en": "night", "phon": "/naɪt/", "cn": "夜晚"},
    {"en": "today", "phon": "/təˈdeɪ/", "cn": "今天"},
    {"en": "tomorrow", "phon": "/təˈmɒr.əʊ/", "cn": "明天"},
    {"en": "yesterday", "phon": "/ˈjes.tə.deɪ/", "cn": "昨天"},
    {"en": "week", "phon": "/wiːk/", "cn": "周"},
    {"en": "month", "phon": "/mʌnθ/", "cn": "月"},
    {"en": "year", "phon": "/jɪər/", "cn": "年"},
    {"en": "spring", "phon": "/sprɪŋ/", "cn": "春天"},
    {"en": "summer", "phon": "/ˈsʌm.ər/", "cn": "夏天"},
    {"en": "autumn", "phon": "/ˈɔː.təm/", "cn": "秋天"},
    {"en": "winter", "phon": "/ˈwɪn.tər/", "cn": "冬天"},
    {"en": "rain", "phon": "/reɪn/", "cn": "雨"},
    {"en": "snow", "phon": "/snəʊ/", "cn": "雪"},
    {"en": "wind", "phon": "/wɪnd/", "cn": "风"},
    {"en": "cloud", "phon": "/klaʊd/", "cn": "云"},
    {"en": "sky", "phon": "/skaɪ/", "cn": "天空"},
    {"en": "earth", "phon": "/ɜːθ/", "cn": "地球"},
    {"en": "sea", "phon": "/siː/", "cn": "海"},
    {"en": "river", "phon": "/ˈrɪv.ər/", "cn": "河"},
    {"en": "mountain", "phon": "/ˈmaʊn.tən/", "cn": "山"},
    {"en": "forest", "phon": "/ˈfɒr.ɪst/", "cn": "森林"},
    {"en": "grass", "phon": "/ɡræs/", "cn": "草"},
    {"en": "stone", "phon": "/stəʊn/", "cn": "石头"},
    {"en": "animal", "phon": "/ˈæn.ɪ.məl/", "cn": "动物"},
    {"en": "horse", "phon": "/hɔːs/", "cn": "马"},
    {"en": "cow", "phon": "/kaʊ/", "cn": "牛"},
    {"en": "pig", "phon": "/pɪɡ/", "cn": "猪"},
    {"en": "sheep", "phon": "/ʃiːp/", "cn": "羊"},
    {"en": "chicken", "phon": "/ˈtʃɪk.ɪn/", "cn": "鸡"},
    {"en": "duck", "phon": "/dʌk/", "cn": "鸭"},
    {"en": "rabbit", "phon": "/ˈræb.ɪt/", "cn": "兔子"},
    {"en": "monkey", "phon": "/ˈmʌŋ.ki/", "cn": "猴子"},
    {"en": "elephant", "phon": "/ˈel.ɪ.fənt/", "cn": "大象"},
    {"en": "tiger", "phon": "/ˈtaɪ.ɡər/", "cn": "老虎"},
    {"en": "lion", "phon": "/ˈlaɪ.ən/", "cn": "狮子"},
    {"en": "bear", "phon": "/beər/", "cn": "熊"},
    {"en": "wolf", "phon": "/wʊlf/", "cn": "狼"},
    {"en": "fox", "phon": "/fɒks/", "cn": "狐狸"},
    {"en": "deer", "phon": "/dɪər/", "cn": "鹿"},
    {"en": "frog", "phon": "/frɒɡ/", "cn": "青蛙"},
    {"en": "snake", "phon": "/sneɪk/", "cn": "蛇"},
    {"en": "turtle", "phon": "/ˈtɜː.təl/", "cn": "乌龟"},
    {"en": "panda", "phon": "/ˈpæn.də/", "cn": "熊猫"},
    {"en": "whale", "phon": "/weɪl/", "cn": "鲸"},
    {"en": "dolphin", "phon": "/ˈdɒl.fɪn/", "cn": "海豚"},
    {"en": "shark", "phon": "/ʃɑːk/", "cn": "鲨鱼"},
    {"en": "family", "phon": "/ˈfæm.əl.i/", "cn": "家庭"},
    {"en": "friend", "phon": "/frend/", "cn": "朋友"},
    {"en": "people", "phon": "/ˈpiː.pəl/", "cn": "人们"},
    {"en": "child", "phon": "/tʃaɪld/", "cn": "孩子"},
    {"en": "baby", "phon": "/ˈbeɪ.bi/", "cn": "婴儿"},
    {"en": "man", "phon": "/mæn/", "cn": "男人"},
    {"en": "woman", "phon": "/ˈwʊm.ən/", "cn": "女人"},
    {"en": "boy", "phon": "/bɔɪ/", "cn": "男孩"},
    {"en": "girl", "phon": "/ɡɜːl/", "cn": "女孩"},
    {"en": "name", "phon": "/neɪm/", "cn": "名字"},
    {"en": "age", "phon": "/eɪdʒ/", "cn": "年龄"},
    {"en": "birthday", "phon": "/ˈbɜːθ.deɪ/", "cn": "生日"},
    {"en": "holiday", "phon": "/ˈhɒl.ə.deɪ/", "cn": "假日"},
    {"en": "weekend", "phon": "/ˌwiːkˈend/", "cn": "周末"},
    {"en": "breakfast", "phon": "/ˈbrek.fəst/", "cn": "早餐"},
    {"en": "lunch", "phon": "/lʌntʃ/", "cn": "午餐"},
    {"en": "dinner", "phon": "/ˈdɪn.ər/", "cn": "晚餐"},
    {"en": "food", "phon": "/fuːd/", "cn": "食物"},
    {"en": "fruit", "phon": "/fruːt/", "cn": "水果"},
    {"en": "vegetable", "phon": "/ˈvedʒ.tə.bəl/", "cn": "蔬菜"},
    {"en": "meat", "phon": "/miːt/", "cn": "肉"},
    {"en": "cake", "phon": "/keɪk/", "cn": "蛋糕"},
    {"en": "candy", "phon": "/ˈkæn.di/", "cn": "糖果"},
    {"en": "cookie", "phon": "/ˈkʊk.i/", "cn": "饼干"},
    {"en": "ice cream", "phon": "/ˌaɪs ˈkriːm/", "cn": "冰淇淋"},
    {"en": "juice", "phon": "/dʒuːs/", "cn": "果汁"},
    {"en": "tea", "phon": "/tiː/", "cn": "茶"},
    {"en": "coffee", "phon": "/ˈkɒf.i/", "cn": "咖啡"},
    {"en": "hat", "phon": "/hæt/", "cn": "帽子"},
    {"en": "shirt", "phon": "/ʃɜːt/", "cn": "衬衫"},
    {"en": "shoes", "phon": "/ʃuːz/", "cn": "鞋子"},
    {"en": "socks", "phon": "/sɒks/", "cn": "袜子"},
    {"en": "dress", "phon": "/dres/", "cn": "裙子"},
    {"en": "coat", "phon": "/kəʊt/", "cn": "外套"},
    {"en": "pants", "phon": "/pænts/", "cn": "裤子"},
    {"en": "bag", "phon": "/bæɡ/", "cn": "包"},
    {"en": "clock", "phon": "/klɒk/", "cn": "钟"},
    {"en": "phone", "phon": "/fəʊn/", "cn": "电话"},
    {"en": "computer", "phon": "/kəmˈpjuː.tər/", "cn": "电脑"},
    {"en": "television", "phon": "/ˈtel.ɪ.vɪʒ.ən/", "cn": "电视"},
    {"en": "radio", "phon": "/ˈreɪ.di.əʊ/", "cn": "收音机"},
    {"en": "camera", "phon": "/ˈkæm.ə.rə/", "cn": "相机"},
    {"en": "music", "phon": "/ˈmjuː.zɪk/", "cn": "音乐"},
    {"en": "song", "phon": "/sɒŋ/", "cn": "歌"},
    {"en": "movie", "phon": "/ˈmuː.vi/", "cn": "电影"},
    {"en": "game", "phon": "/ɡeɪm/", "cn": "游戏"},
    {"en": "sport", "phon": "/spɔːt/", "cn": "运动"},
    {"en": "ball", "phon": "/bɔːl/", "cn": "球"},
    {"en": "toy", "phon": "/tɔɪ/", "cn": "玩具"},
]

GRADE_2 = [
    {"en": "always", "phon": "/ˈɔːl.weɪz/", "cn": "总是"},
    {"en": "never", "phon": "/ˈnev.ər/", "cn": "从不"},
    {"en": "sometimes", "phon": "/ˈsʌm.taɪmz/", "cn": "有时"},
    {"en": "usually", "phon": "/ˈjuː.ʒu.əl.i/", "cn": "通常"},
    {"en": "often", "phon": "/ˈɒf.ən/", "cn": "经常"},
    {"en": "already", "phon": "/ɔːlˈred.i/", "cn": "已经"},
    {"en": "beautiful", "phon": "/ˈbjuː.tɪ.fəl/", "cn": "漂亮的"},
    {"en": "clever", "phon": "/ˈklev.ər/", "cn": "聪明的"},
    {"en": "quiet", "phon": "/ˈkwaɪ.ət/", "cn": "安静的"},
    {"en": "loud", "phon": "/laʊd/", "cn": "大声的"},
    {"en": "clean", "phon": "/kliːn/", "cn": "干净的"},
    {"en": "dirty", "phon": "/ˈdɜː.ti/", "cn": "脏的"},
    {"en": "full", "phon": "/fʊl/", "cn": "满的"},
    {"en": "empty", "phon": "/ˈemp.ti/", "cn": "空的"},
    {"en": "heavy", "phon": "/ˈhev.i/", "cn": "重的"},
    {"en": "light", "phon": "/laɪt/", "cn": "轻的"},
    {"en": "hard", "phon": "/hɑːd/", "cn": "硬的"},
    {"en": "soft", "phon": "/sɒft/", "cn": "软的"},
    {"en": "sharp", "phon": "/ʃɑːp/", "cn": "锋利的"},
    {"en": "smooth", "phon": "/smuːð/", "cn": "光滑的"},
    {"en": "rough", "phon": "/rʌf/", "cn": "粗糙的"},
    {"en": "straight", "phon": "/streɪt/", "cn": "直的"},
    {"en": "round", "phon": "/raʊnd/", "cn": "圆的"},
    {"en": "square", "phon": "/skweər/", "cn": "方的"},
    {"en": "deep", "phon": "/diːp/", "cn": "深的"},
    {"en": "wide", "phon": "/waɪd/", "cn": "宽的"},
    {"en": "narrow", "phon": "/ˈnær.əʊ/", "cn": "窄的"},
    {"en": "first", "phon": "/fɜːst/", "cn": "第一"},
    {"en": "last", "phon": "/læst/", "cn": "最后"},
    {"en": "next", "phon": "/nekst/", "cn": "下一个"},
    {"en": "early", "phon": "/ˈɜː.li/", "cn": "早的"},
    {"en": "late", "phon": "/leɪt/", "cn": "晚的"},
    {"en": "ready", "phon": "/ˈred.i/", "cn": "准备好的"},
    {"en": "busy", "phon": "/ˈbɪz.i/", "cn": "忙碌的"},
    {"en": "free", "phon": "/friː/", "cn": "自由的"},
    {"en": "safe", "phon": "/seɪf/", "cn": "安全的"},
    {"en": "dangerous", "phon": "/ˈdeɪn.dʒər.əs/", "cn": "危险的"},
    {"en": "same", "phon": "/seɪm/", "cn": "相同的"},
    {"en": "different", "phon": "/ˈdɪf.ər.ənt/", "cn": "不同的"},
    {"en": "easy", "phon": "/ˈiː.zi/", "cn": "容易的"},
    {"en": "difficult", "phon": "/ˈdɪf.ɪ.kəlt/", "cn": "困难的"},
    {"en": "simple", "phon": "/ˈsɪm.pəl/", "cn": "简单的"},
    {"en": "important", "phon": "/ɪmˈpɔː.tənt/", "cn": "重要的"},
    {"en": "special", "phon": "/ˈspeʃ.əl/", "cn": "特别的"},
    {"en": "wonderful", "phon": "/ˈwʌn.də.fəl/", "cn": "精彩的"},
    {"en": "terrible", "phon": "/ˈter.ə.bəl/", "cn": "糟糕的"},
    {"en": "correct", "phon": "/kəˈrekt/", "cn": "正确的"},
    {"en": "wrong", "phon": "/rɒŋ/", "cn": "错误的"},
    {"en": "true", "phon": "/truː/", "cn": "真的"},
    {"en": "false", "phon": "/fɔːls/", "cn": "假的"},
    {"en": "whole", "phon": "/həʊl/", "cn": "整个"},
    {"en": "half", "phon": "/hæf/", "cn": "一半"},
    {"en": "enough", "phon": "/ɪˈnʌf/", "cn": "足够"},
    {"en": "little", "phon": "/ˈlɪt.əl/", "cn": "少的"},
    {"en": "much", "phon": "/mʌtʃ/", "cn": "多的"},
    {"en": "more", "phon": "/mɔːr/", "cn": "更多"},
    {"en": "less", "phon": "/les/", "cn": "更少"},
    {"en": "best", "phon": "/best/", "cn": "最好的"},
    {"en": "worst", "phon": "/wɜːst/", "cn": "最坏的"},
    {"en": "better", "phon": "/ˈbet.ər/", "cn": "更好的"},
    {"en": "worse", "phon": "/wɜːs/", "cn": "更坏的"},
    {"en": "other", "phon": "/ˈʌð.ər/", "cn": "其他"},
    {"en": "another", "phon": "/əˈnʌð.ər/", "cn": "另一个"},
    {"en": "each", "phon": "/iːtʃ/", "cn": "每个"},
    {"en": "every", "phon": "/ˈev.ri/", "cn": "每一"},
    {"en": "both", "phon": "/bəʊθ/", "cn": "两者都"},
    {"en": "neither", "phon": "/ˈnaɪ.ðər/", "cn": "两者都不"},
    {"en": "either", "phon": "/ˈaɪ.ðər/", "cn": "任一"},
    {"en": "nobody", "phon": "/ˈnəʊ.bə.di/", "cn": "没有人"},
    {"en": "somebody", "phon": "/ˈsʌm.bə.di/", "cn": "某人"},
    {"en": "everybody", "phon": "/ˈev.ri.bə.di/", "cn": "每个人"},
    {"en": "everything", "phon": "/ˈev.ri.θɪŋ/", "cn": "一切"},
    {"en": "nothing", "phon": "/ˈnʌθ.ɪŋ/", "cn": "没有什么"},
    {"en": "something", "phon": "/ˈsʌm.θɪŋ/", "cn": "某事"},
    {"en": "anything", "phon": "/ˈen.i.θɪŋ/", "cn": "任何事"},
    {"en": "where", "phon": "/weər/", "cn": "哪里"},
    {"en": "when", "phon": "/wen/", "cn": "什么时候"},
    {"en": "why", "phon": "/waɪ/", "cn": "为什么"},
    {"en": "how", "phon": "/haʊ/", "cn": "怎样"},
    {"en": "what", "phon": "/wɒt/", "cn": "什么"},
    {"en": "who", "phon": "/huː/", "cn": "谁"},
    {"en": "which", "phon": "/wɪtʃ/", "cn": "哪个"},
    {"en": "whose", "phon": "/huːz/", "cn": "谁的"},
    {"en": "before", "phon": "/bɪˈfɔːr/", "cn": "在...之前"},
    {"en": "after", "phon": "/ˈæf.tər/", "cn": "在...之后"},
    {"en": "during", "phon": "/ˈdjʊə.rɪŋ/", "cn": "在...期间"},
    {"en": "until", "phon": "/ənˈtɪl/", "cn": "直到"},
    {"en": "since", "phon": "/sɪns/", "cn": "自从"},
    {"en": "while", "phon": "/waɪl/", "cn": "当...时"},
    {"en": "because", "phon": "/bɪˈkɒz/", "cn": "因为"},
    {"en": "although", "phon": "/ɔːlˈðəʊ/", "cn": "虽然"},
    {"en": "however", "phon": "/haʊˈev.ər/", "cn": "然而"},
    {"en": "therefore", "phon": "/ˈðeə.fɔːr/", "cn": "因此"},
    {"en": "maybe", "phon": "/ˈmeɪ.bi/", "cn": "也许"},
    {"en": "perhaps", "phon": "/pəˈhæps/", "cn": "可能"},
    {"en": "probably", "phon": "/ˈprɒb.ə.bli/", "cn": "大概"},
    {"en": "really", "phon": "/ˈriː.əl.i/", "cn": "真的"},
    {"en": "quite", "phon": "/kwaɪt/", "cn": "相当"},
    {"en": "very", "phon": "/ˈver.i/", "cn": "非常"},
    {"en": "too", "phon": "/tuː/", "cn": "太"},
    {"en": "also", "phon": "/ˈɔːl.səʊ/", "cn": "也"},
    {"en": "just", "phon": "/dʒʌst/", "cn": "只是"},
    {"en": "only", "phon": "/ˈəʊn.li/", "cn": "只有"},
    {"en": "even", "phon": "/ˈiː.vən/", "cn": "甚至"},
    {"en": "still", "phon": "/stɪl/", "cn": "仍然"},
    {"en": "again", "phon": "/əˈɡen/", "cn": "再次"},
    {"en": "once", "phon": "/wʌns/", "cn": "曾经"},
    {"en": "twice", "phon": "/twaɪs/", "cn": "两次"},
    {"en": "soon", "phon": "/suːn/", "cn": "很快"},
    {"en": "later", "phon": "/ˈleɪ.tər/", "cn": "稍后"},
    {"en": "ago", "phon": "/əˈɡəʊ/", "cn": "以前"},
    {"en": "now", "phon": "/naʊ/", "cn": "现在"},
    {"en": "here", "phon": "/hɪər/", "cn": "这里"},
    {"en": "there", "phon": "/ðeər/", "cn": "那里"},
    {"en": "inside", "phon": "/ˌɪnˈsaɪd/", "cn": "里面"},
    {"en": "outside", "phon": "/ˌaʊtˈsaɪd/", "cn": "外面"},
    {"en": "above", "phon": "/əˈbʌv/", "cn": "上面"},
    {"en": "below", "phon": "/bɪˈləʊ/", "cn": "下面"},
    {"en": "between", "phon": "/bɪˈtwiːn/", "cn": "之间"},
    {"en": "beside", "phon": "/bɪˈsaɪd/", "cn": "旁边"},
    {"en": "behind", "phon": "/bɪˈhaɪnd/", "cn": "后面"},
    {"en": "front", "phon": "/frʌnt/", "cn": "前面"},
    {"en": "left", "phon": "/left/", "cn": "左边"},
    {"en": "right", "phon": "/raɪt/", "cn": "右边"},
    {"en": "north", "phon": "/nɔːθ/", "cn": "北"},
    {"en": "south", "phon": "/saʊθ/", "cn": "南"},
    {"en": "east", "phon": "/iːst/", "cn": "东"},
    {"en": "west", "phon": "/west/", "cn": "西"},
    {"en": "near", "phon": "/nɪər/", "cn": "近的"},
    {"en": "far", "phon": "/fɑːr/", "cn": "远的"},
    {"en": "quickly", "phon": "/ˈkwɪk.li/", "cn": "快速地"},
    {"en": "slowly", "phon": "/ˈsləʊ.li/", "cn": "慢慢地"},
    {"en": "carefully", "phon": "/ˈkeə.fəl.i/", "cn": "仔细地"},
    {"en": "happily", "phon": "/ˈhæp.ɪ.li/", "cn": "快乐地"},
    {"en": "sadly", "phon": "/ˈsæd.li/", "cn": "伤心地"},
    {"en": "loudly", "phon": "/ˈlaʊd.li/", "cn": "大声地"},
    {"en": "quietly", "phon": "/ˈkwaɪ.ət.li/", "cn": "安静地"},
    {"en": "gently", "phon": "/ˈdʒent.li/", "cn": "轻轻地"},
    {"en": "warmly", "phon": "/ˈwɔːm.li/", "cn": "温暖地"},
    {"en": "coldly", "phon": "/ˈkəʊld.li/", "cn": "冷淡地"},
    {"en": "friendly", "phon": "/ˈfrend.li/", "cn": "友好的"},
    {"en": "lonely", "phon": "/ˈləʊn.li/", "cn": "孤独的"},
    {"en": "lovely", "phon": "/ˈlʌv.li/", "cn": "可爱的"},
    {"en": "ugly", "phon": "/ˈʌɡ.li/", "cn": "丑的"},
    {"en": "pretty", "phon": "/ˈprɪt.i/", "cn": "漂亮的"},
    {"en": "handsome", "phon": "/ˈhæn.səm/", "cn": "英俊的"},
    {"en": "young", "phon": "/jʌŋ/", "cn": "年轻的"},
    {"en": "kind", "phon": "/kaɪnd/", "cn": "善良的"},
    {"en": "strict", "phon": "/strɪkt/", "cn": "严格的"},
    {"en": "patient", "phon": "/ˈpeɪ.ʃənt/", "cn": "有耐心的"},
    {"en": "brave", "phon": "/breɪv/", "cn": "勇敢的"},
    {"en": "shy", "phon": "/ʃaɪ/", "cn": "害羞的"},
    {"en": "polite", "phon": "/pəˈlaɪt/", "cn": "有礼貌的"},
    {"en": "rude", "phon": "/ruːd/", "cn": "粗鲁的"},
    {"en": "honest", "phon": "/ˈɒn.ɪst/", "cn": "诚实的"},
    {"en": "lazy", "phon": "/ˈleɪ.zi/", "cn": "懒惰的"},
    {"en": "active", "phon": "/ˈæk.tɪv/", "cn": "活跃的"},
    {"en": "calm", "phon": "/kɑːm/", "cn": "平静的"},
    {"en": "angry", "phon": "/ˈæŋ.ɡri/", "cn": "生气的"},
    {"en": "afraid", "phon": "/əˈfreɪd/", "cn": "害怕的"},
    {"en": "wonderful", "phon": "/ˈwʌn.də.fəl/", "cn": "精彩的"},
    {"en": "amazing", "phon": "/əˈmeɪ.zɪŋ/", "cn": "惊人的"},
    {"en": "interesting", "phon": "/ˈɪn.trəs.tɪŋ/", "cn": "有趣的"},
    {"en": "boring", "phon": "/ˈbɔːr.ɪŋ/", "cn": "无聊的"},
    {"en": "exciting", "phon": "/ɪkˈsaɪ.tɪŋ/", "cn": "令人兴奋的"},
    {"en": "surprising", "phon": "/səˈpraɪ.zɪŋ/", "cn": "令人惊讶的"},
    {"en": "disappointing", "phon": "/ˌdɪs.əˈpɔɪn.tɪŋ/", "cn": "令人失望的"},
    {"en": "confusing", "phon": "/kənˈfjuː.zɪŋ/", "cn": "令人困惑的"},
    {"en": "embarrassing", "phon": "/ɪmˈbær.ə.sɪŋ/", "cn": "令人尴尬的"},
    {"en": "relaxing", "phon": "/rɪˈlæk.sɪŋ/", "cn": "令人放松的"},
]

GRADE_3 = [
    {"en": "adventure", "phon": "/ədˈven.tʃər/", "cn": "冒险"},
    {"en": "ancient", "phon": "/ˈeɪn.ʃənt/", "cn": "古老的"},
    {"en": "ancient", "phon": "/ˈeɪn.ʃənt/", "cn": "古代的"},
    {"en": "ancient", "phon": "/ˈeɪn.ʃənt/", "cn": "远古的"},
    {"en": "ancient", "phon": "/ˈeɪn.ʃənt/", "cn": "老的"},
    {"en": "ancient", "phon": "/ˈeɪn.ʃənt/", "cn": "以往的"},
    {"en": "ancient", "phon": "/ˈeɪn.ʃənt/", "cn": "古老的"},
    {"en": "ancient", "phon": "/ˈeɪn.ʃənt/", "cn": "古代的"},
    {"en": "ancient", "phon": "/ˈeɪn.ʃənt/", "cn": "远古的"},
    {"en": "ancient", "phon": "/ˈeɪn.ʃənt/", "cn": "老的"},
]


def generate_grade(grade_num, category_words):
    all_words = []
    for cat_name, words in category_words:
        all_words.extend(words)
    return all_words[:350]


output_dir = "/home/code/gitronlee.github.io/src/data/word-tetris"

for f in glob.glob(os.path.join(output_dir, "grade-*.json")):
    os.remove(f)

total = 0
for grade in range(1, 10):
    if grade == 1:
        words = GRADE_1
    elif grade == 2:
        words = GRADE_2
    else:
        words = []

    for sub in range(1, 8):
        filename = f"grade-{grade}-{sub}.json"
        start = (sub - 1) * 50
        end = start + 50
        level_words = words[start:end] if start < len(words) else []

        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(level_words, f, ensure_ascii=False, indent=2)
        total += len(level_words)
        print(f"{filename}: {len(level_words)} words")

print(f"\nTotal: {total}")
