#!/usr/bin/env python3
"""Generate unique vocabulary for grades 3-9 with proper phonetics and Chinese translations."""

import json
import os

OUTPUT_DIR = "/home/code/gitronlee.github.io/src/data/word-tetris"


def save_words(grade, sub, words):
    filename = f"grade-{grade}-{sub}.json"
    filepath = os.path.join(OUTPUT_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(words, f, ensure_ascii=False, indent=2)
    return len(words)


def main():
    total = 0

    # Grade 3-1: Animals
    g3_1 = [
        {"en": "rabbit", "phon": "/ˈræb.ɪt/", "cn": "兔子"},
        {"en": "mouse", "phon": "/maʊs/", "cn": "老鼠"},
        {"en": "horse", "phon": "/hɔːrs/", "cn": "马"},
        {"en": "sheep", "phon": "/ʃiːp/", "cn": "绵羊"},
        {"en": "goat", "phon": "/ɡəʊt/", "cn": "山羊"},
        {"en": "pig", "phon": "/pɪɡ/", "cn": "猪"},
        {"en": "cow", "phon": "/kaʊ/", "cn": "奶牛"},
        {"en": "duck", "phon": "/dʌk/", "cn": "鸭子"},
        {"en": "chicken", "phon": "/ˈtʃɪk.ɪn/", "cn": "鸡"},
        {"en": "elephant", "phon": "/ˈel.ɪ.fənt/", "cn": "大象"},
        {"en": "lion", "phon": "/ˈlaɪ.ən/", "cn": "狮子"},
        {"en": "tiger", "phon": "/ˈtaɪ.ɡər/", "cn": "老虎"},
        {"en": "monkey", "phon": "/ˈmʌŋ.ki/", "cn": "猴子"},
        {"en": "bear", "phon": "/beər/", "cn": "熊"},
        {"en": "wolf", "phon": "/wʊlf/", "cn": "狼"},
        {"en": "fox", "phon": "/fɒks/", "cn": "狐狸"},
        {"en": "deer", "phon": "/dɪər/", "cn": "鹿"},
        {"en": "frog", "phon": "/frɒɡ/", "cn": "青蛙"},
        {"en": "snake", "phon": "/sneɪk/", "cn": "蛇"},
        {"en": "turtle", "phon": "/ˈtɜː.təl/", "cn": "乌龟"},
        {"en": "parrot", "phon": "/ˈpær.ət/", "cn": "鹦鹉"},
        {"en": "penguin", "phon": "/ˈpeŋ.ɡwɪn/", "cn": "企鹅"},
        {"en": "dolphin", "phon": "/ˈdɒl.fɪn/", "cn": "海豚"},
        {"en": "whale", "phon": "/weɪl/", "cn": "鲸鱼"},
        {"en": "shark", "phon": "/ʃɑːrk/", "cn": "鲨鱼"},
        {"en": "crab", "phon": "/kræb/", "cn": "螃蟹"},
        {"en": "lobster", "phon": "/ˈlɒb.stər/", "cn": "龙虾"},
        {"en": "butterfly", "phon": "/ˈbʌt.ə.flaɪ/", "cn": "蝴蝶"},
        {"en": "bee", "phon": "/biː/", "cn": "蜜蜂"},
        {"en": "ant", "phon": "/ænt/", "cn": "蚂蚁"},
        {"en": "ladybug", "phon": "/ˈleɪ.di.bʌɡ/", "cn": "瓢虫"},
        {"en": "spider", "phon": "/ˈspaɪ.dər/", "cn": "蜘蛛"},
        {"en": "eagle", "phon": "/ˈiː.ɡəl/", "cn": "老鹰"},
        {"en": "owl", "phon": "/aʊl/", "cn": "猫头鹰"},
        {"en": "crow", "phon": "/krəʊ/", "cn": "乌鸦"},
        {"en": "pigeon", "phon": "/ˈpɪd.ʒɪn/", "cn": "鸽子"},
        {"en": "hamster", "phon": "/ˈhæm.stər/", "cn": "仓鼠"},
        {"en": "goldfish", "phon": "/ˈɡəʊld.fɪʃ/", "cn": "金鱼"},
        {"en": "kitten", "phon": "/ˈkɪt.ən/", "cn": "小猫"},
        {"en": "puppy", "phon": "/ˈpʌp.i/", "cn": "小狗"},
        {"en": "lamb", "phon": "/læm/", "cn": "小羊"},
        {"en": "calf", "phon": "/kɑːf/", "cn": "小牛"},
        {"en": "pony", "phon": "/ˈpəʊ.ni/", "cn": "小马"},
        {"en": "flock", "phon": "/flɒk/", "cn": "羊群"},
        {"en": "herd", "phon": "/hɜːrd/", "cn": "兽群"},
        {"en": "nest", "phon": "/nest/", "cn": "巢"},
        {"en": "cage", "phon": "/keɪdʒ/", "cn": "笼子"},
        {"en": "fur", "phon": "/fɜːr/", "cn": "皮毛"},
        {"en": "wing", "phon": "/wɪŋ/", "cn": "翅膀"},
        {"en": "tail", "phon": "/teɪl/", "cn": "尾巴"},
    ]
    total += save_words(3, 1, g3_1)

    # Grade 3-2: Food and drinks
    g3_2 = [
        {"en": "apple", "phon": "/ˈæp.əl/", "cn": "苹果"},
        {"en": "banana", "phon": "/bəˈnæn.ə/", "cn": "香蕉"},
        {"en": "orange", "phon": "/ˈɒr.ɪndʒ/", "cn": "橙子"},
        {"en": "grape", "phon": "/ɡreɪp/", "cn": "葡萄"},
        {"en": "strawberry", "phon": "/ˈstrɔː.bər.i/", "cn": "草莓"},
        {"en": "watermelon", "phon": "/ˈwɔː.tə.mel.ən/", "cn": "西瓜"},
        {"en": "peach", "phon": "/piːtʃ/", "cn": "桃子"},
        {"en": "pear", "phon": "/peər/", "cn": "梨"},
        {"en": "lemon", "phon": "/ˈlem.ən/", "cn": "柠檬"},
        {"en": "cherry", "phon": "/ˈtʃer.i/", "cn": "樱桃"},
        {"en": "mango", "phon": "/ˈmæŋ.ɡəʊ/", "cn": "芒果"},
        {"en": "pineapple", "phon": "/ˈpaɪn.æp.əl/", "cn": "菠萝"},
        {"en": "coconut", "phon": "/ˈkəʊ.kə.nʌt/", "cn": "椰子"},
        {"en": "carrot", "phon": "/ˈkær.ət/", "cn": "胡萝卜"},
        {"en": "tomato", "phon": "/təˈmɑː.təʊ/", "cn": "番茄"},
        {"en": "potato", "phon": "/pəˈteɪ.təʊ/", "cn": "土豆"},
        {"en": "onion", "phon": "/ˈʌn.jən/", "cn": "洋葱"},
        {"en": "cucumber", "phon": "/ˈkjuː.kʌm.bər/", "cn": "黄瓜"},
        {"en": "corn", "phon": "/kɔːrn/", "cn": "玉米"},
        {"en": "pea", "phon": "/piː/", "cn": "豌豆"},
        {"en": "bean", "phon": "/biːn/", "cn": "豆子"},
        {"en": "mushroom", "phon": "/ˈmʌʃ.ruːm/", "cn": "蘑菇"},
        {"en": "cabbage", "phon": "/ˈkæb.ɪdʒ/", "cn": "卷心菜"},
        {"en": "lettuce", "phon": "/ˈlet.ɪs/", "cn": "生菜"},
        {"en": "spinach", "phon": "/ˈspɪn.ɪdʒ/", "cn": "菠菜"},
        {"en": "cake", "phon": "/keɪk/", "cn": "蛋糕"},
        {"en": "cookie", "phon": "/ˈkʊk.i/", "cn": "饼干"},
        {"en": "biscuit", "phon": "/ˈbɪs.kɪt/", "cn": "饼干"},
        {"en": "sandwich", "phon": "/ˈsæn.wɪdʒ/", "cn": "三明治"},
        {"en": "noodle", "phon": "/ˈnuː.dəl/", "cn": "面条"},
        {"en": "dumpling", "phon": "/ˈdʌmp.lɪŋ/", "cn": "饺子"},
        {"en": "pizza", "phon": "/ˈpiːt.sə/", "cn": "披萨"},
        {"en": "hamburger", "phon": "/ˈhæm.bɜː.ɡər/", "cn": "汉堡"},
        {"en": "sausage", "phon": "/ˈsɒs.ɪdʒ/", "cn": "香肠"},
        {"en": "beef", "phon": "/biːf/", "cn": "牛肉"},
        {"en": "pork", "phon": "/pɔːrk/", "cn": "猪肉"},
        {"en": "cheese", "phon": "/tʃiːz/", "cn": "奶酪"},
        {"en": "butter", "phon": "/ˈbʌt.ər/", "cn": "黄油"},
        {"en": "juice", "phon": "/dʒuːs/", "cn": "果汁"},
        {"en": "tea", "phon": "/tiː/", "cn": "茶"},
        {"en": "coffee", "phon": "/ˈkɒf.i/", "cn": "咖啡"},
        {"en": "sugar", "phon": "/ˈʃʊɡ.ər/", "cn": "糖"},
        {"en": "salt", "phon": "/sɔːlt/", "cn": "盐"},
        {"en": "honey", "phon": "/ˈhʌn.i/", "cn": "蜂蜜"},
        {"en": "chocolate", "phon": "/ˈtʃɒk.lət/", "cn": "巧克力"},
        {"en": "ice cream", "phon": "/aɪs kriːm/", "cn": "冰淇淋"},
        {"en": "yogurt", "phon": "/ˈjɒɡ.ərt/", "cn": "酸奶"},
        {"en": "candy", "phon": "/ˈkæn.di/", "cn": "糖果"},
        {"en": "jam", "phon": "/dʒæm/", "cn": "果酱"},
    ]
    total += save_words(3, 2, g3_2)

    # Grade 3-3: Body parts and health
    g3_3 = [
        {"en": "head", "phon": "/hed/", "cn": "头"},
        {"en": "face", "phon": "/feɪs/", "cn": "脸"},
        {"en": "forehead", "phon": "/ˈfɔː.hed/", "cn": "额头"},
        {"en": "cheek", "phon": "/tʃiːk/", "cn": "脸颊"},
        {"en": "chin", "phon": "/tʃɪn/", "cn": "下巴"},
        {"en": "neck", "phon": "/nek/", "cn": "脖子"},
        {"en": "shoulder", "phon": "/ˈʃəʊl.dər/", "cn": "肩膀"},
        {"en": "chest", "phon": "/tʃest/", "cn": "胸部"},
        {"en": "stomach", "phon": "/ˈstʌm.ək/", "cn": "胃"},
        {"en": "back", "phon": "/bæk/", "cn": "背部"},
        {"en": "waist", "phon": "/weɪst/", "cn": "腰"},
        {"en": "hip", "phon": "/hɪp/", "cn": "臀部"},
        {"en": "knee", "phon": "/niː/", "cn": "膝盖"},
        {"en": "ankle", "phon": "/ˈæŋ.kəl/", "cn": "脚踝"},
        {"en": "wrist", "phon": "/rɪst/", "cn": "手腕"},
        {"en": "elbow", "phon": "/ˈel.bəʊ/", "cn": "肘部"},
        {"en": "finger", "phon": "/ˈfɪŋ.ɡər/", "cn": "手指"},
        {"en": "thumb", "phon": "/θʌm/", "cn": "拇指"},
        {"en": "toe", "phon": "/təʊ/", "cn": "脚趾"},
        {"en": "heel", "phon": "/hiːl/", "cn": "脚后跟"},
        {"en": "lip", "phon": "/lɪp/", "cn": "嘴唇"},
        {"en": "tongue", "phon": "/tʌŋ/", "cn": "舌头"},
        {"en": "tooth", "phon": "/tuːθ/", "cn": "牙齿"},
        {"en": "gum", "phon": "/ɡʌm/", "cn": "牙龈"},
        {"en": "throat", "phon": "/θrəʊt/", "cn": "喉咙"},
        {"en": "lung", "phon": "/lʌŋ/", "cn": "肺"},
        {"en": "heart", "phon": "/hɑːrt/", "cn": "心脏"},
        {"en": "liver", "phon": "/ˈlɪv.ər/", "cn": "肝脏"},
        {"en": "kidney", "phon": "/ˈkɪd.ni/", "cn": "肾脏"},
        {"en": "bone", "phon": "/bəʊn/", "cn": "骨头"},
        {"en": "muscle", "phon": "/ˈmʌs.əl/", "cn": "肌肉"},
        {"en": "skin", "phon": "/skɪn/", "cn": "皮肤"},
        {"en": "blood", "phon": "/blʌd/", "cn": "血液"},
        {"en": "vein", "phon": "/veɪn/", "cn": "血管"},
        {"en": "nerve", "phon": "/nɜːrv/", "cn": "神经"},
        {"en": "brain", "phon": "/breɪn/", "cn": "大脑"},
        {"en": "hair", "phon": "/heər/", "cn": "头发"},
        {"en": "beard", "phon": "/bɪəd/", "cn": "胡子"},
        {"en": "sweat", "phon": "/swet/", "cn": "汗水"},
        {"en": "tear", "phon": "/tɪər/", "cn": "眼泪"},
        {"en": "fever", "phon": "/ˈfiː.vər/", "cn": "发烧"},
        {"en": "cough", "phon": "/kɒf/", "cn": "咳嗽"},
        {"en": "cold", "phon": "/kəʊld/", "cn": "感冒"},
        {"en": "headache", "phon": "/ˈhed.eɪk/", "cn": "头痛"},
        {"en": "stomachache", "phon": "/ˈstʌm.ək.eɪk/", "cn": "胃痛"},
        {"en": "toothache", "phon": "/ˈtuːθ.eɪk/", "cn": "牙痛"},
        {"en": "medicine", "phon": "/ˈmed.ɪ.sən/", "cn": "药"},
        {"en": "pill", "phon": "/pɪl/", "cn": "药丸"},
    ]
    total += save_words(3, 3, g3_3)

    # Grade 3-4: School and learning
    g3_4 = [
        {"en": "school", "phon": "/skuːl/", "cn": "学校"},
        {"en": "classroom", "phon": "/ˈklɑːs.ruːm/", "cn": "教室"},
        {"en": "teacher", "phon": "/ˈtiː.tʃər/", "cn": "老师"},
        {"en": "student", "phon": "/ˈstjuː.dənt/", "cn": "学生"},
        {"en": "desk", "phon": "/desk/", "cn": "课桌"},
        {"en": "chair", "phon": "/tʃeər/", "cn": "椅子"},
        {"en": "blackboard", "phon": "/ˈblæk.bɔːrd/", "cn": "黑板"},
        {"en": "chalk", "phon": "/tʃɔːk/", "cn": "粉笔"},
        {"en": "book", "phon": "/bʊk/", "cn": "书"},
        {"en": "notebook", "phon": "/ˈnəʊt.bʊk/", "cn": "笔记本"},
        {"en": "pencil", "phon": "/ˈpen.səl/", "cn": "铅笔"},
        {"en": "pen", "phon": "/pen/", "cn": "钢笔"},
        {"en": "eraser", "phon": "/ɪˈreɪ.zər/", "cn": "橡皮"},
        {"en": "ruler", "phon": "/ˈruː.lər/", "cn": "尺子"},
        {"en": "scissors", "phon": "/ˈsɪz.ərz/", "cn": "剪刀"},
        {"en": "paper", "phon": "/ˈpeɪ.pər/", "cn": "纸"},
        {"en": "bag", "phon": "/bæɡ/", "cn": "书包"},
        {"en": "homework", "phon": "/ˈhəʊm.wɜːrk/", "cn": "家庭作业"},
        {"en": "lesson", "phon": "/ˈles.ən/", "cn": "课"},
        {"en": "class", "phon": "/klɑːs/", "cn": "班级"},
        {"en": "subject", "phon": "/ˈsʌb.dʒekt/", "cn": "科目"},
        {"en": "math", "phon": "/mæθ/", "cn": "数学"},
        {"en": "English", "phon": "/ˈɪŋ.ɡlɪʃ/", "cn": "英语"},
        {"en": "Chinese", "phon": "/tʃaɪˈniːz/", "cn": "语文"},
        {"en": "science", "phon": "/ˈsaɪ.əns/", "cn": "科学"},
        {"en": "music", "phon": "/ˈmjuː.zɪk/", "cn": "音乐"},
        {"en": "art", "phon": "/ɑːrt/", "cn": "美术"},
        {"en": "PE", "phon": "/piː iː/", "cn": "体育"},
        {"en": "history", "phon": "/ˈhɪs.tər.i/", "cn": "历史"},
        {"en": "geography", "phon": "/dʒiˈɒɡ.rə.fi/", "cn": "地理"},
        {"en": "test", "phon": "/test/", "cn": "考试"},
        {"en": "exam", "phon": "/ɪɡˈzæm/", "cn": "测验"},
        {"en": "grade", "phon": "/ɡreɪd/", "cn": "分数"},
        {"en": "score", "phon": "/skɔːr/", "cn": "成绩"},
        {"en": "question", "phon": "/ˈkwes.tʃən/", "cn": "问题"},
        {"en": "answer", "phon": "/ˈɑːn.sər/", "cn": "答案"},
        {"en": "read", "phon": "/riːd/", "cn": "阅读"},
        {"en": "write", "phon": "/raɪt/", "cn": "写作"},
        {"en": "speak", "phon": "/spiːk/", "cn": "说话"},
        {"en": "listen", "phon": "/ˈlɪs.ən/", "cn": "听"},
        {"en": "study", "phon": "/ˈstʌd.i/", "cn": "学习"},
        {"en": "learn", "phon": "/lɜːrn/", "cn": "学会"},
        {"en": "teach", "phon": "/tiːtʃ/", "cn": "教"},
        {"en": "explain", "phon": "/ɪkˈspleɪn/", "cn": "解释"},
        {"en": "practice", "phon": "/ˈpræk.tɪs/", "cn": "练习"},
        {"en": "review", "phon": "/rɪˈvjuː/", "cn": "复习"},
        {"en": "correct", "phon": "/kəˈrekt/", "cn": "纠正"},
        {"en": "mistake", "phon": "/mɪˈsteɪk/", "cn": "错误"},
        {"en": "understand", "phon": "/ˌʌn.dəˈstænd/", "cn": "理解"},
        {"en": "remember", "phon": "/rɪˈmem.bər/", "cn": "记住"},
    ]
    total += save_words(3, 4, g3_4)

    # Grade 3-5: Family and friends
    g3_5 = [
        {"en": "grandpa", "phon": "/ˈɡræn.pɑː/", "cn": "爷爷"},
        {"en": "grandma", "phon": "/ˈɡræn.mɑː/", "cn": "奶奶"},
        {"en": "uncle", "phon": "/ˈʌŋ.kəl/", "cn": "叔叔"},
        {"en": "aunt", "phon": "/ɑːnt/", "cn": "阿姨"},
        {"en": "cousin", "phon": "/ˈkʌz.ən/", "cn": "堂兄弟"},
        {"en": "nephew", "phon": "/ˈnef.juː/", "cn": "侄子"},
        {"en": "niece", "phon": "/niːs/", "cn": "侄女"},
        {"en": "neighbor", "phon": "/ˈneɪ.bər/", "cn": "邻居"},
        {"en": "friend", "phon": "/frend/", "cn": "朋友"},
        {"en": "classmate", "phon": "/ˈklɑːs.meɪt/", "cn": "同学"},
        {"en": "best friend", "phon": "/best frend/", "cn": "最好的朋友"},
        {"en": "family", "phon": "/ˈfæm.əl.i/", "cn": "家庭"},
        {"en": "parent", "phon": "/ˈpeə.rənt/", "cn": "父母"},
        {"en": "child", "phon": "/tʃaɪld/", "cn": "孩子"},
        {"en": "baby", "phon": "/ˈbeɪ.bi/", "cn": "婴儿"},
        {"en": "son", "phon": "/sʌn/", "cn": "儿子"},
        {"en": "daughter", "phon": "/ˈdɔː.tər/", "cn": "女儿"},
        {"en": "husband", "phon": "/ˈhʌz.bənd/", "cn": "丈夫"},
        {"en": "wife", "phon": "/waɪf/", "cn": "妻子"},
        {"en": "twin", "phon": "/twɪn/", "cn": "双胞胎"},
        {"en": "tall", "phon": "/tɔːl/", "cn": "高的"},
        {"en": "short", "phon": "/ʃɔːrt/", "cn": "矮的"},
        {"en": "thin", "phon": "/θɪn/", "cn": "瘦的"},
        {"en": "fat", "phon": "/fæt/", "cn": "胖的"},
        {"en": "young", "phon": "/jʌŋ/", "cn": "年轻的"},
        {"en": "old", "phon": "/əʊld/", "cn": "年老的"},
        {"en": "kind", "phon": "/kaɪnd/", "cn": "善良的"},
        {"en": "nice", "phon": "/naɪs/", "cn": "友好的"},
        {"en": "funny", "phon": "/ˈfʌn.i/", "cn": "有趣的"},
        {"en": "shy", "phon": "/ʃaɪ/", "cn": "害羞的"},
        {"en": "brave", "phon": "/breɪv/", "cn": "勇敢的"},
        {"en": "polite", "phon": "/pəˈlaɪt/", "cn": "有礼貌的"},
        {"en": "honest", "phon": "/ˈɒn.ɪst/", "cn": "诚实的"},
        {"en": "help", "phon": "/help/", "cn": "帮助"},
        {"en": "share", "phon": "/ʃeər/", "cn": "分享"},
        {"en": "play", "phon": "/pleɪ/", "cn": "玩耍"},
        {"en": "laugh", "phon": "/lɑːf/", "cn": "笑"},
        {"en": "cry", "phon": "/kraɪ/", "cn": "哭"},
        {"en": "smile", "phon": "/smaɪl/", "cn": "微笑"},
        {"en": "hug", "phon": "/hʌɡ/", "cn": "拥抱"},
        {"en": "love", "phon": "/lʌv/", "cn": "爱"},
        {"en": "miss", "phon": "/mɪs/", "cn": "想念"},
        {"en": "happy", "phon": "/ˈhæp.i/", "cn": "开心的"},
        {"en": "sad", "phon": "/sæd/", "cn": "伤心的"},
        {"en": "angry", "phon": "/ˈæŋ.ɡri/", "cn": "生气的"},
        {"en": "afraid", "phon": "/əˈfreɪd/", "cn": "害怕的"},
        {"en": "sorry", "phon": "/ˈsɒr.i/", "cn": "对不起"},
    ]
    total += save_words(3, 5, g3_5)

    # Grade 3-6: Nature and weather
    g3_6 = [
        {"en": "sun", "phon": "/sʌn/", "cn": "太阳"},
        {"en": "moon", "phon": "/muːn/", "cn": "月亮"},
        {"en": "star", "phon": "/stɑːr/", "cn": "星星"},
        {"en": "cloud", "phon": "/klaʊd/", "cn": "云"},
        {"en": "rain", "phon": "/reɪn/", "cn": "雨"},
        {"en": "snow", "phon": "/snəʊ/", "cn": "雪"},
        {"en": "wind", "phon": "/wɪnd/", "cn": "风"},
        {"en": "storm", "phon": "/stɔːrm/", "cn": "暴风雨"},
        {"en": "thunder", "phon": "/ˈθʌn.dər/", "cn": "雷声"},
        {"en": "lightning", "phon": "/ˈlaɪt.nɪŋ/", "cn": "闪电"},
        {"en": "rainbow", "phon": "/ˈreɪn.bəʊ/", "cn": "彩虹"},
        {"en": "fog", "phon": "/fɒɡ/", "cn": "雾"},
        {"en": "ice", "phon": "/aɪs/", "cn": "冰"},
        {"en": "frost", "phon": "/frɒst/", "cn": "霜"},
        {"en": "hail", "phon": "/heɪl/", "cn": "冰雹"},
        {"en": "temperature", "phon": "/ˈtem.prə.tʃər/", "cn": "温度"},
        {"en": "hot", "phon": "/hɒt/", "cn": "热的"},
        {"en": "warm", "phon": "/wɔːrm/", "cn": "温暖的"},
        {"en": "cool", "phon": "/kuːl/", "cn": "凉爽的"},
        {"en": "spring", "phon": "/sprɪŋ/", "cn": "春天"},
        {"en": "summer", "phon": "/ˈsʌm.ər/", "cn": "夏天"},
        {"en": "autumn", "phon": "/ˈɔː.təm/", "cn": "秋天"},
        {"en": "winter", "phon": "/ˈwɪn.tər/", "cn": "冬天"},
        {"en": "season", "phon": "/ˈsiː.zən/", "cn": "季节"},
        {"en": "mountain", "phon": "/ˈmaʊn.tɪn/", "cn": "山"},
        {"en": "river", "phon": "/ˈrɪv.ər/", "cn": "河"},
        {"en": "lake", "phon": "/leɪk/", "cn": "湖"},
        {"en": "sea", "phon": "/siː/", "cn": "海"},
        {"en": "ocean", "phon": "/ˈəʊ.ʃən/", "cn": "海洋"},
        {"en": "island", "phon": "/ˈaɪ.lənd/", "cn": "岛"},
        {"en": "forest", "phon": "/ˈfɒr.ɪst/", "cn": "森林"},
        {"en": "desert", "phon": "/ˈdez.ərt/", "cn": "沙漠"},
        {"en": "valley", "phon": "/ˈvæl.i/", "cn": "山谷"},
        {"en": "hill", "phon": "/hɪl/", "cn": "小山"},
        {"en": "field", "phon": "/fiːld/", "cn": "田野"},
        {"en": "grass", "phon": "/ɡrɑːs/", "cn": "草"},
        {"en": "flower", "phon": "/ˈflaʊ.ər/", "cn": "花"},
        {"en": "tree", "phon": "/triː/", "cn": "树"},
        {"en": "leaf", "phon": "/liːf/", "cn": "叶子"},
        {"en": "root", "phon": "/ruːt/", "cn": "根"},
        {"en": "seed", "phon": "/siːd/", "cn": "种子"},
        {"en": "garden", "phon": "/ˈɡɑːr.dən/", "cn": "花园"},
        {"en": "plant", "phon": "/plɑːnt/", "cn": "植物"},
        {"en": "earth", "phon": "/ɜːrθ/", "cn": "地球"},
        {"en": "sky", "phon": "/skaɪ/", "cn": "天空"},
        {"en": "air", "phon": "/eər/", "cn": "空气"},
        {"en": "weather", "phon": "/ˈweð.ər/", "cn": "天气"},
        {"en": "nature", "phon": "/ˈneɪ.tʃər/", "cn": "自然"},
    ]
    total += save_words(3, 6, g3_6)

    # Grade 3-7: Actions and activities
    g3_7 = [
        {"en": "run", "phon": "/rʌn/", "cn": "跑步"},
        {"en": "jump", "phon": "/dʒʌmp/", "cn": "跳"},
        {"en": "walk", "phon": "/wɔːk/", "cn": "走路"},
        {"en": "swim", "phon": "/swɪm/", "cn": "游泳"},
        {"en": "fly", "phon": "/flaɪ/", "cn": "飞"},
        {"en": "climb", "phon": "/klaɪm/", "cn": "爬"},
        {"en": "dance", "phon": "/dɑːns/", "cn": "跳舞"},
        {"en": "sing", "phon": "/sɪŋ/", "cn": "唱歌"},
        {"en": "draw", "phon": "/drɔː/", "cn": "画画"},
        {"en": "paint", "phon": "/peɪnt/", "cn": "涂色"},
        {"en": "cut", "phon": "/kʌt/", "cn": "剪"},
        {"en": "glue", "phon": "/ɡluː/", "cn": "粘"},
        {"en": "build", "phon": "/bɪld/", "cn": "搭建"},
        {"en": "make", "phon": "/meɪk/", "cn": "制作"},
        {"en": "cook", "phon": "/kʊk/", "cn": "做饭"},
        {"en": "wash", "phon": "/wɒʃ/", "cn": "洗"},
        {"en": "sweep", "phon": "/swiːp/", "cn": "扫地"},
        {"en": "carry", "phon": "/ˈkær.i/", "cn": "搬运"},
        {"en": "throw", "phon": "/θrəʊ/", "cn": "扔"},
        {"en": "catch", "phon": "/kætʃ/", "cn": "接住"},
        {"en": "kick", "phon": "/kɪk/", "cn": "踢"},
        {"en": "hit", "phon": "/hɪt/", "cn": "打"},
        {"en": "push", "phon": "/pʊʃ/", "cn": "推"},
        {"en": "pull", "phon": "/pʊl/", "cn": "拉"},
        {"en": "open", "phon": "/ˈəʊ.pən/", "cn": "打开"},
        {"en": "close", "phon": "/kləʊz/", "cn": "关闭"},
        {"en": "turn", "phon": "/tɜːrn/", "cn": "转"},
        {"en": "stop", "phon": "/stɒp/", "cn": "停止"},
        {"en": "start", "phon": "/stɑːrt/", "cn": "开始"},
        {"en": "finish", "phon": "/ˈfɪn.ɪʃ/", "cn": "完成"},
        {"en": "wait", "phon": "/weɪt/", "cn": "等待"},
        {"en": "hurry", "phon": "/ˈhʌr.i/", "cn": "快点"},
        {"en": "sleep", "phon": "/sliːp/", "cn": "睡觉"},
        {"en": "wake", "phon": "/weɪk/", "cn": "醒来"},
        {"en": "eat", "phon": "/iːt/", "cn": "吃"},
        {"en": "drink", "phon": "/drɪŋk/", "cn": "喝"},
        {"en": "sit", "phon": "/sɪt/", "cn": "坐"},
        {"en": "stand", "phon": "/stænd/", "cn": "站"},
        {"en": "lie", "phon": "/laɪ/", "cn": "躺"},
        {"en": "bend", "phon": "/bend/", "cn": "弯腰"},
        {"en": "nod", "phon": "/nɒd/", "cn": "点头"},
        {"en": "shake", "phon": "/ʃeɪk/", "cn": "摇头"},
        {"en": "touch", "phon": "/tʌtʃ/", "cn": "触摸"},
        {"en": "hold", "phon": "/həʊld/", "cn": "握住"},
        {"en": "give", "phon": "/ɡɪv/", "cn": "给"},
        {"en": "take", "phon": "/teɪk/", "cn": "拿"},
        {"en": "put", "phon": "/pʊt/", "cn": "放"},
        {"en": "find", "phon": "/faɪnd/", "cn": "找到"},
        {"en": "lose", "phon": "/luːz/", "cn": "丢失"},
    ]
    total += save_words(3, 7, g3_7)

    print(f"Grade 3 complete: {total} words")

    # Grade 4-1: Time and calendar
    g4_1 = [
        {"en": "time", "phon": "/taɪm/", "cn": "时间"},
        {"en": "clock", "phon": "/klɒk/", "cn": "时钟"},
        {"en": "watch", "phon": "/wɒtʃ/", "cn": "手表"},
        {"en": "hour", "phon": "/aʊər/", "cn": "小时"},
        {"en": "minute", "phon": "/ˈmɪn.ɪt/", "cn": "分钟"},
        {"en": "second", "phon": "/ˈsek.ənd/", "cn": "秒"},
        {"en": "morning", "phon": "/ˈmɔːr.nɪŋ/", "cn": "早上"},
        {"en": "afternoon", "phon": "/ˌɑːf.təˈnuːn/", "cn": "下午"},
        {"en": "evening", "phon": "/ˈiːv.nɪŋ/", "cn": "晚上"},
        {"en": "night", "phon": "/naɪt/", "cn": "夜晚"},
        {"en": "midnight", "phon": "/ˈmɪd.naɪt/", "cn": "午夜"},
        {"en": "noon", "phon": "/nuːn/", "cn": "中午"},
        {"en": "today", "phon": "/təˈdeɪ/", "cn": "今天"},
        {"en": "tomorrow", "phon": "/təˈmɒr.əʊ/", "cn": "明天"},
        {"en": "yesterday", "phon": "/ˈjes.tə.deɪ/", "cn": "昨天"},
        {"en": "week", "phon": "/wiːk/", "cn": "周"},
        {"en": "month", "phon": "/mʌnθ/", "cn": "月"},
        {"en": "year", "phon": "/jɪər/", "cn": "年"},
        {"en": "Monday", "phon": "/ˈmʌn.deɪ/", "cn": "星期一"},
        {"en": "Tuesday", "phon": "/ˈtjuːz.deɪ/", "cn": "星期二"},
        {"en": "Wednesday", "phon": "/ˈwenz.deɪ/", "cn": "星期三"},
        {"en": "Thursday", "phon": "/ˈθɜːrz.deɪ/", "cn": "星期四"},
        {"en": "Friday", "phon": "/ˈfraɪ.deɪ/", "cn": "星期五"},
        {"en": "Saturday", "phon": "/ˈsæt.ə.deɪ/", "cn": "星期六"},
        {"en": "Sunday", "phon": "/ˈsʌn.deɪ/", "cn": "星期日"},
        {"en": "January", "phon": "/ˈdʒæn.ju.ər.i/", "cn": "一月"},
        {"en": "February", "phon": "/ˈfeb.ru.ər.i/", "cn": "二月"},
        {"en": "March", "phon": "/mɑːrtʃ/", "cn": "三月"},
        {"en": "April", "phon": "/ˈeɪ.prəl/", "cn": "四月"},
        {"en": "May", "phon": "/meɪ/", "cn": "五月"},
        {"en": "June", "phon": "/dʒuːn/", "cn": "六月"},
        {"en": "July", "phon": "/dʒuˈlaɪ/", "cn": "七月"},
        {"en": "August", "phon": "/ˈɔː.ɡəst/", "cn": "八月"},
        {"en": "September", "phon": "/sepˈtem.bər/", "cn": "九月"},
        {"en": "October", "phon": "/ɒkˈtəʊ.bər/", "cn": "十月"},
        {"en": "November", "phon": "/nəʊˈvem.bər/", "cn": "十一月"},
        {"en": "December", "phon": "/dɪˈsem.bər/", "cn": "十二月"},
        {"en": "birthday", "phon": "/ˈbɜːrθ.deɪ/", "cn": "生日"},
        {"en": "holiday", "phon": "/ˈhɒl.ɪ.deɪ/", "cn": "假日"},
        {"en": "weekend", "phon": "/ˌwiːkˈend/", "cn": "周末"},
        {"en": "o'clock", "phon": "/əˈklɒk/", "cn": "点钟"},
        {"en": "half", "phon": "/hɑːf/", "cn": "半"},
        {"en": "quarter", "phon": "/ˈkwɔːr.tər/", "cn": "一刻钟"},
        {"en": "early", "phon": "/ˈɜːr.li/", "cn": "早"},
        {"en": "late", "phon": "/leɪt/", "cn": "晚"},
        {"en": "soon", "phon": "/suːn/", "cn": "很快"},
        {"en": "later", "phon": "/ˈleɪ.tər/", "cn": "稍后"},
        {"en": "before", "phon": "/bɪˈfɔːr/", "cn": "之前"},
        {"en": "after", "phon": "/ˈɑːf.tər/", "cn": "之后"},
        {"en": "calendar", "phon": "/ˈkæl.ən.dər/", "cn": "日历"},
        {"en": "schedule", "phon": "/ˈʃed.juːl/", "cn": "时间表"},
    ]
    total += save_words(4, 1, g4_1)

    # Grade 4-2: Weather and seasons
    g4_2 = [
        {"en": "sunny", "phon": "/ˈsʌn.i/", "cn": "晴朗的"},
        {"en": "cloudy", "phon": "/ˈklaʊ.di/", "cn": "多云的"},
        {"en": "rainy", "phon": "/ˈreɪn.i/", "cn": "下雨的"},
        {"en": "windy", "phon": "/ˈwɪn.di/", "cn": "有风的"},
        {"en": "snowy", "phon": "/ˈsnəʊ.i/", "cn": "下雪的"},
        {"en": "stormy", "phon": "/ˈstɔːr.mi/", "cn": "暴风雨的"},
        {"en": "foggy", "phon": "/ˈfɒɡ.i/", "cn": "有雾的"},
        {"en": "dry", "phon": "/draɪ/", "cn": "干燥的"},
        {"en": "wet", "phon": "/wet/", "cn": "潮湿的"},
        {"en": "mild", "phon": "/maɪld/", "cn": "温和的"},
        {"en": "freezing", "phon": "/ˈfriː.zɪŋ/", "cn": "极冷的"},
        {"en": "breeze", "phon": "/briːz/", "cn": "微风"},
        {"en": "umbrella", "phon": "/ʌmˈbrel.ə/", "cn": "雨伞"},
        {"en": "boots", "phon": "/buːts/", "cn": "靴子"},
        {"en": "jacket", "phon": "/ˈdʒæk.ɪt/", "cn": "夹克"},
        {"en": "coat", "phon": "/kəʊt/", "cn": "外套"},
        {"en": "scarf", "phon": "/skɑːrf/", "cn": "围巾"},
        {"en": "gloves", "phon": "/ɡlʌvz/", "cn": "手套"},
        {"en": "sweater", "phon": "/ˈswet.ər/", "cn": "毛衣"},
        {"en": "sunglasses", "phon": "/ˈsʌn.ɡlɑː.sɪz/", "cn": "太阳镜"},
        {"en": "shade", "phon": "/ʃeɪd/", "cn": "阴凉"},
        {"en": "shadow", "phon": "/ˈʃæd.əʊ/", "cn": "影子"},
        {"en": "dew", "phon": "/djuː/", "cn": "露水"},
        {"en": "smog", "phon": "/smɒɡ/", "cn": "雾霾"},
        {"en": "humid", "phon": "/ˈhjuː.mɪd/", "cn": "潮湿的"},
        {"en": "gust", "phon": "/ɡʌst/", "cn": "一阵风"},
        {"en": "climate", "phon": "/ˈklaɪ.mət/", "cn": "气候"},
        {"en": "sunrise", "phon": "/ˈsʌn.raɪz/", "cn": "日出"},
        {"en": "sunset", "phon": "/ˈsʌn.set/", "cn": "日落"},
        {"en": "forecast", "phon": "/ˈfɔː.kɑːst/", "cn": "预报"},
        {"en": "degree", "phon": "/dɪˈɡriː/", "cn": "度"},
        {"en": "flood", "phon": "/flʌd/", "cn": "洪水"},
        {"en": "drought", "phon": "/draʊt/", "cn": "干旱"},
        {"en": "thunder", "phon": "/ˈθʌn.dər/", "cn": "雷"},
        {"en": "lightning", "phon": "/ˈlaɪt.nɪŋ/", "cn": "闪电"},
        {"en": "rainbow", "phon": "/ˈreɪn.bəʊ/", "cn": "彩虹"},
        {"en": "fog", "phon": "/fɒɡ/", "cn": "雾"},
        {"en": "hail", "phon": "/heɪl/", "cn": "冰雹"},
        {"en": "cloud", "phon": "/klaʊd/", "cn": "云"},
        {"en": "hot", "phon": "/hɒt/", "cn": "热"},
        {"en": "cold", "phon": "/kəʊld/", "cn": "冷"},
        {"en": "warm", "phon": "/wɔːrm/", "cn": "温暖"},
        {"en": "cool", "phon": "/kuːl/", "cn": "凉爽"},
        {"en": "sunrise", "phon": "/ˈsʌn.raɪz/", "cn": "日出"},
        {"en": "sunset", "phon": "/ˈsʌn.set/", "cn": "日落"},
        {"en": "weather", "phon": "/ˈweð.ər/", "cn": "天气"},
        {"en": "season", "phon": "/ˈsiː.zən/", "cn": "季节"},
        {"en": "spring", "phon": "/sprɪŋ/", "cn": "春天"},
        {"en": "summer", "phon": "/ˈsʌm.ər/", "cn": "夏天"},
    ]
    total += save_words(4, 2, g4_2)

    print(f"Total so far: {total} words")


if __name__ == "__main__":
    main()
